services:
  postgres:
    image: postgres:15
    container_name: measure-postgres
    environment:
      POSTGRES_USER: measure
      POSTGRES_PASSWORD: measure123
      POSTGRES_DB: measure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U measure"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: measure-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://measure:measure123@postgres:5432/measure
      - SECRET_KEY=${SECRET_KEY:-09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7}
      - AUTH_USERS=${AUTH_USERS:-admin:password}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn api.main:app --host 0.0.0.0 --reload

  web:
    image: nginx:alpine
    container_name: measure-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  postgres_data: